#!/bin/bash
"""
Example usage of mutate_sequences_target_avoid.py
"""

echo "Example usage of mutate_sequences_target_avoid.py"
echo "=============================================="

echo ""
echo "1. Basic usage with GLUT6 vs GLUT5:"
echo "python mutate_sequences_target_avoid.py --target GLUT6 --avoid GLUT5"

echo ""
echo "2. Custom parameters:"
echo "python mutate_sequences_target_avoid.py --target GLUT7 --avoid EXC --iterations 50 --seq-length 100"

echo ""
echo "3. Fewer sequences for faster testing:"
echo "python mutate_sequences_target_avoid.py --target L2.3.IT --avoid L4.IT --n-seqs 50 --adalead-rounds 10"

echo ""
echo "4. Custom output prefix:"
echo "python mutate_sequences_target_avoid.py --target GLUT6 --avoid GLUT5 --output-prefix my_experiment"

echo ""
echo "5. Show help:"
echo "python mutate_sequences_target_avoid.py --help"

echo ""
echo "Note: Make sure to update the MODEL_PATHS dictionary in the script with your actual model paths!"
echo ""
echo "Wandb tracking:"
echo "- All runs are logged to the 'cnn_pipeline_cortex_enhancers' project"
echo "- Run names follow the pattern: mutation_script_{target}_vs_{avoid}"
echo "- Metrics tracked: reward values, target/avoid predictions over iterations"
echo "- Summary table shows initial vs final performance"
echo ""
echo "Model loading:"
echo "- Automatically handles custom metrics (PearsonCorrelation, etc.)"
echo "- Falls back to compile=False if custom objects fail"
echo "- Compatible with cnn_pipeline trained models"
echo "- Automatically detects model input shape and sequence length"
echo "- Creates sequences with correct dimensions for your models"
echo ""
echo "Progress tracking:"
echo "- AdaLead optimization: Shows progress through rounds and turns"
echo "- Saturation mutagenesis: Shows progress through iterations and sequences"
echo "- Position testing: Shows progress through each sequence position"
echo "- Real-time metrics: Best reward and improvement counts"
echo ""
echo "Performance optimization:"
echo "- GPU memory growth enabled for better memory management"
echo "- Automatic batch size adjustment based on GPU memory"
echo "- Batch processing for systematic mutations (default: 128)"
echo "- Parallel sequence processing for saturation mutagenesis"
echo "- Memory error handling with automatic batch size reduction"
echo "- Use --mutation-batch-size to adjust mutation batch size"