# sweep-config.yaml: Config for `wandb` hyperparameter sweep.
# Usage: sbatch sweep.sb
#
# Note: To run the sweep in an interactive session (e.g. for debugging),
#     wandb sweep sweep-config.yaml
# This is not recommended for actual training (use sbatch instead).

program: train.py

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "-config"
  - "config-base.yaml"
  - ${args}

project: liver-regression

method: random

metric:
  name: val_mean_squared_error
  goal: minimize

parameters:
  lr_init:
    distribution: log_uniform_values
    min: 1.e-5
    max: 3.e-3

  conv_filters:
    values: [200, 250, 300, 400, 500]

  dense_filters:
    values: [50, 100, 150, 200, 250]

  num_conv_layers:
    values: [3, 4, 5, 6, 7]

  num_dense_layers:
    values: [0, 1, 2]
  
  dropout_rate_dense:
    values: [0.05, 0.1, 0.2]

  dropout_rate_conv:
    values: [0.3, 0.4, 0.5]
